# BASE UI
ColorColumn: '- Grey32'
Conceal: ''
Cursor: ''
CursorIM: ''
CursorColumn: '- Grey32'
CursorLine: '- Grey32'
CursorLineNr: 'SteelBlue1'
Directory: 'LightSkyBlue1'
DiffAdd: '- GreyGreen27'
DiffChange: '- GreyBlue30'
DiffDelete: 'Indianred1 GreyRed23'
DiffText: ''
ErrorMsg: 'Indianred1'
VertSplit: '- Grey28'
Folded: 'Grey66 Grey20'
FoldColumn: 'Grey66 Grey20'
SignColumn: 'Grey99 Grey28'
IncSearch: 'White Black'
LineNr: 'Grey44'
MatchParen: 'Indianred1'
ModeMsg: ''
MoreMsg: ''
NonText: 'Grey44'
Normal: 'SpringGreen3'
PMenu: 'GreyDA GreyBlue30'
PMenuSel: 'GreyBlue30 Khaki3'
PmenuSbar: 'GreyBlue30 Khaki3'
PmenuThumb: 'GreyBlue30 Khaki3'
Question: 'Khaki3'
Search: 'White - r'
SpecialKey: 'Grey44'
SpellBad: 'Indianred1'
SpellLocal: 'Tan'
SpellCap: 'SandyBrown'
SpellRare: 'SteelBlue1'
StatusLine: 'Grey1D Grey66'
StatusLineNC: 'Grey99 Grey44'
TabLine: 'Grey99 Grey44'
TabLineFill: '- Grey44'
TabLineSel: 'Khaki3'
Title: 'LightSkyBlue1'
Visual: '- GreyBlue23'
VisualNOS: '- GreyBlue23'
WarningMsg: 'Indianred1'
WildMenu: 'Grey28 Khaki3'
# BASE SYNTAX
Comment: 'DarkOrange3'
Constant: 'DeepSkyBlue3'
String: 'PaleTurquoise4' # Constant
Character: 'SpringGreen2' # Constant
Boolean: '' # Constant
Number: '' # Constant
Float: '' # Constant
Identifier: ''
Function: 'SkyBlue2' # Identifier
Statement: 'PaleTurquoise4'  # assign etc
Conditional: 'SpringGreen2' # Statement
Repeat: 'SpringGreen2' # Statement
Label: 'Tan' # Statement
Operator: 'Khaki3' # Statement
Keyword: '' # Statement
Exception: '' # Statement
PreProc: ''
Include: '' # PreProc
Define: 'DarkOrange' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'SpringGreen2'
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: 'Tan' # verilog operator
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: ''
Todo: 'Indianred1'
